spring:
  session:
    store-type: jdbc
    jdbc:
      initializer:
        enabled: true
      schema: classpath:org/springframework/session/jdbc/schema-mysql.sql
  datasource:
    url: jdbc:mysql://localhost:3306/sessiondb
    username: root
    password: welcome
    driver-class-name: com.mysql.jdbc.Driver

server:
  port: 8081

---

spring:
  profiles: test
spring.datasource:
  url: jdbc:h2:mem:db;DB_CLOSE_DELAY=-1
  username: sa
  password: sa
  driver-class-name: org.h2.Driver        
  

